### ISSUE TITLE
Create script to build installer .exe or .msi for Windows (runnable on windows 7 x64 and newer)

### ISSUE THREAD

**Issue by wu-emma** [BitgesellOfficial/bitgesell#23]
### Task Description

The aim of this task is to revisit creation of the Windows installable package (the Nullsoft installer is currenly used) of BGL Core. It's largely the same script and process as the Bitcoin Core installation script, with same dependencies and build process.
It uses VS2019 image to build the installation executable package.
https://github.com/wu-emma/bitgesell/blob/master/.appveyor.yml
  
You can create free account on AppVeyor.com at https://www.appveyor.com/

### Solution steps
- Ensure that windows build is working (including Qt wallet), this will require Visual Studio (download VS2019 Community Edition if you don't have one installed);
- There are dependencies installed using vcpkg, but the more complicated thing is Qt, which should be installed by hand (check existing AppVeyor script link https://github.com/sipsorcery/qt_win_binary/releases/download/v1.6/Qt5.9.8_x64_static_vs2019.zip);
- Fix dependencies or project settings (if needed) in build_msvc;
- Sign up to AppVeyor free tier;
- Fix AppVeyor script in .appveyor.yml

### Acceptance criteria
- AppVeyor has a free tier -- please sign up for it, project is public, so it is allowed;
- AppVeyor can automatically build Windows installable package for Windows x64 platform;
- Along with pull request (which probably would be rather short), provide sample of built setup executable and short notes of integrating/fetching built artifacts from AppVeyour build.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.75 ETH (301.62 USD @ $402.16/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $952,056.61 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 266 years from now.
Please review their action plans below:


**1) [molecula451](https://gitcoin.co/molecula451) has been approved to start work.**

Will create a script to build the windows installer as per requirements
**2) [touhonoob](https://gitcoin.co/touhonoob) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?mutate_worker_action=approve&worker=touhonoob) | [reject worker](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?mutate_worker_action=reject&worker=touhonoob))_.**

- manually build the project under vs2019
- write a bat/powershell script to build MSI installer & make sure the installer work
- test the installer build script on appveyor
- publish the link to built artifact(.msi) to the pull request comment section

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028).

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by wu-emma** [comment]
HI Paul! @molecula451 
How're you doing? Have you been working on the subject? Update would be really appreciated.

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by touhonoob** [comment]
Hi @wu-emma I can take over the task if you don't mind.

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
@molecula451 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=1) | [3 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=3) | [5 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=5) | [10 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=10) | [100 days](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 0.75 ETH (359.46 USD @ $479.28/ETH) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/wu-emma/bitgesell/23/100024028).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://chat.gitcoin.co/'>Gitcoin Chat</a>
* $1,049,019.26 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
